# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3625c61f7585dd2ab149c4c25e148e65f490ce3b6bd7697e14cc22f97acfa06534cd8f8748c3ce7090891e27580bc10fe874e47de3f26ba48888c344282dea5c

test:
  secret_key_base: 2a4b5422d98232102f34d2429649ec926c056b08f9c2159e25f24d2c5fd10f3ab19a38ad835dce4787d6675209341cab4eb882f26e2a94af6121e270deaa420e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
